[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  external_node_modules = ["@prisma/client", "next", "react", "react-dom", "sharp"]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]

  [functions.node_bundler_flags]
  minify = true
  tree-shaking = true
  bundle = true
  platform = "node"
  target = "node18"
  external = ["@prisma/client", "next", "react", "react-dom", "sharp"]

[build.environment]
  NEXT_RUNTIME = "nodejs"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  framework = "next"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 