[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]

  [functions.node_bundler_flags]
  minify = true
  tree-shaking = true

[build.environment]
  NEXT_RUNTIME = "nodejs"

[dev]
  framework = "next"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs" 